node_info:
    - type_name: default
      description: Default node specification
      rootfs_mode: memorized
      packages: node-agent
      supported_archs: x86, x86_64
kernels:
    - kernel_url: ftp://blik-products-distribution/images/kernel-default-x86
      arch: x86
    - kernel_url: ftp://blik-products-distribution/images/kernel-default-x86_64
      arch: x86_64
